name: 2. Winter arrives 🌨

on:
  issues:
    types: opened

jobs:
  snowfall:
    name: Make it snow

    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Proceed to chapter 2 ("Winter arrives")
        run: ./.github/scripts/update-repo.sh snowfall
